# Generated by Django 2.2.6 on 2019-10-19 12:03

from django.db import migrations, models
import malltranslator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=malltranslator.models.getImagePath)),
                ('spam', models.BooleanField(default=False)),
            ],
        ),
    ]
